name = "system-hono"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
CORS_DOMAINS = "*"

[[env.development.vars]]
ENVIRONMENT = "development"
CORS_DOMAINS = "https://xn--fctz62bir0aba.top"

[env.production]
name = "system-hono-prod"
vars = { ENVIRONMENT = "production", CORS_DOMAINS = "*" }

compatibility_flags = ["nodejs_compat"]
